adding greatful exit (issue #10)
orbitlens/stellar-notifier pull request #22
Opened 2020-03-16 17:22 UTC by Ebioro

2020-03-17 07:12 UTC, orbitlens requested changes

2020-03-17 07:12 UTC, orbitlens commented on api/server-initialization.js
> +const mongoose = require('mongoose');
We don't know exactly which storage provider a user plugged-in. So doing it only for the mongodb case seems prone to errors. How about adding a finalizer method to the [StorageProvider](https://github.com/stellar-expert/operations-notifier/blob/93aa567c72c4c8a17cc2e14308ee80f9ef467326/persistence-layer/storage-provider.js) class and implementing it in derived providers?

Something like
```
finalize() {
    return mongoose.disconnect()
}
```

Then we can implement the graceful exit code in the provider-agnostic fashion, and it won't break when some implements, say, PostgreSQL plugin.

2020-03-18 09:38 UTC, Ebioro commented
done in latest commit

2020-04-02 21:41 UTC, orbitlens approved these changes
Looks great. Thanks!

2020-04-02 21:43 UTC, merged